CREATE TABLE users(
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL  UNIQUE,
  user_password VARCHAR(200) NOT NULL,
  country_code VARCHAR(10) NOT NULL,
  phone_number VARCHAR(50) NOT NULL UNIQUE,
  authy_status VARCHAR(50) NOT NULL DEFAULT 'unverified',
  authy_id VARCHAR(100) DEFAULT NULL UNIQUE,
  tocken VARCHAR(100) DEFAULT NULL,
  reg_date TIMESTAMP
)